# .cnb.yml

# 手动触发：构建并推送镜像到制品库
$:
  web_trigger_build_image:
    - name: build-and-push
      runner:
        cpus: 8
      services:
        - docker
      stages:
        - name: build image
          script: docker build -f .ide/Dockerfile -t docker.cnb.cool/yueweix/gateway_zero/rust-dev:latest .
        - name: push image
          script: docker push docker.cnb.cool/yueweix/gateway_zero/rust-dev:latest

  # 日常使用：直接用制品库的镜像启动开发环境
  vscode:
    - name: rust-dev
      runner:
        cpus: 8
      docker:
        image: docker.cnb.cool/yueweix/gateway_zero/rust-dev:latest
      services:
        - vscode
        - docker
